### ISSUE TITLE
Cam Maximizing

### ISSUE THREAD

**Issue by Webby7866** [Technetium1/TinychatTheme#1]
Anyway i could code in a BYpass to the PRO Max Cam and make a button to max a cam like in the tinychat enhancement skin? i love your set up wayyyy better then then it but i love there max cam feature anyway to combine it?

**Comment by Technetium1** [comment]
@Webby7866 I plan to implement a cam maxing feature. Unfortunately even if you do get scammed into paying for a TinyChat subscription, you *still* don't get a working maximize. So there is no way to do any 'override'. TES has their own functions specific to their code, I would drop it in if it were possible.

**Comment by Technetium1** [comment]
https://github.com/Technetium1/TinychatTheme/commit/e637dbd72af0bb79e0ed064fcb10e986b20454c4
